name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setting up .env
        run: |
          echo "${{ secrets.SCHEDULE_PRODUCTION_ENV }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp-based tag
        id: tag
        run: echo "TIMESTAMP_TAG=$(date +'%y%m%d')" >> $GITHUB_ENV

  
      - name: Build Docker image (Laravel)
        run: |
          docker build --no-cache -t alvarobk/scheduleapp:${{ env.TIMESTAMP_TAG }} .

      - name: Build Docker image (Nginx)
        run: |
          docker build --no-cache -t alvarobk/schedulenginx:${{ env.TIMESTAMP_TAG }} ./docker/nginx

      - name: Scan Laravel Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: alvarobk/scheduleapp:${{ env.TIMESTAMP_TAG }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln'  # Disable secret scanning

      - name: Scan Nginx Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: alvarobk/schedulenginx:${{ env.TIMESTAMP_TAG }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln'  # Disable secret scanning

      - name: Docker push images
        run: |
          docker push alvarobk/scheduleapp:${{ env.TIMESTAMP_TAG }}
          docker push alvarobk/schedulenginx:${{ env.TIMESTAMP_TAG }}

      #- name: Scan PHP dependencies for vulnerabilities with Enlightn
        #run: |
         # docker run --rm alvarobk/scheduleapp:${{ env.TIMESTAMP_TAG }} php artisan enlightn --no-interaction

      - name: Scan JavaScript code for vulnerabilities with ESLint
        run: npx eslint .

      - name: Scan JavaScript dependencies for vulnerabilities with npm audit
        run: npm audit --audit-level=high

      - name: Scan code for security issues with GitHub CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript,php'
      - run: github/codeql-action/analyze@v1

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost'
          docker-name: 'owasp/zap2docker-weekly'