name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setting up .env
        run: |
          echo "${{ vars.BEVERAGE_DEVELOPMENT_ENV }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp-based tag
        id: tag
        run: echo "::set-output name=TIMESTAMP_TAG::$(date +'%y%m%d')"

      - name: Build Docker image (Laravel)
        run: |
          docker build --no-cache -t bcxdev/beverageappdev:${{ steps.tag.outputs.TIMESTAMP_TAG }} .
          
      - name: Build Docker image (Nginx)
        run: |
          docker build --no-cache -t bcxdev/beveragenginxdev:${{ steps.tag.outputs.TIMESTAMP_TAG }} ./docker/nginx

      - name: Docker push images
        run: |
          docker push bcxdev/beverageappdev:${{ steps.tag.outputs.TIMESTAMP_TAG }}
          docker push bcxdev/beveragenginxdev:${{ steps.tag.outputs.TIMESTAMP_TAG }}
